forthy/finatra.g8

src/main/g8/src/main/scala/$package__packaged$/client/RichHttpClient.scala
+ Added Failed Fast switch to rich HTTP client when deals with HTTP communication
=> Rich HTTP client enhancement

src/main/g8/build.sbt, src/main/g8/default.properties
+ Switched to Lightbend Scala 2.12.2
+ Removed redundantly defined Swagger dependencies
=> 06282017 patch

src/main/g8/src/main/scala/$package__packaged$/sse/ServerSentEventsResponse.scala
+ added Server Sent Events support (Finatra will never officially support SSE)
=> 20170713-sse-support

src/main/g8/default.properties
+ Updated Scala version from 2.12.2 to 2.12.3
+ Updated sbt version from 0.13.15 to 0.13.16
=> 20170730 - Scala and SBT update

src/main/g8/build.sbt, src/main/g8/src/main/scala/$package__packaged$/util/AdaptableLogging.scala
+ refactored AdaptableLogging.scala and removed the direct use of Option.get
+ updated dependent libraries and sbt plugins
=> 20170809-refactoring-lib-updates

src/main/g8/build.sbt, src/main/g8/default.properties
+ Added a property `docker_repository` for configuration when creating a project
=> 20170816-docker-repository-setting

src/main/g8/build.sbt
+ Upgraded Finatra from `2.11.0` to `2.12.0`
=> 20170817-finatra-2.12.0-upgrade

src/main/g8/build.sbt
+ Upgraded Finatra from `2.11.0` to `2.12.0`
+ Changed Docker base image from `openjdk:8-jre-alpine` to `openjdk:8-jre-slim`
=> 2017-Sep-28-update

src/main/g8/build.sbt, src/main/g8/project/sbt-native-packager.sbt
+ Upgraded Finagle related projects, such as Finatra
+ Upgraded sbt-native-packager
+ Added Docker support extension to set-native-packager
=> 2018-jan-update

src/main/g8/build.sbt
+ Enabled Docker Content Trust (https://docs.docker.com/engine/security/trust/content_trust/#image-tags-and-content-trust)
=> Added Docker Content Trust

src/main/g8/build.sbt, src/main/g8/default.properties, src/main/g8/project/plugins.sbt
+ Updated Scala from 2.12.5 to 2.12.5
+ Upgraded libraries
=> Scala 2.12.6 update

src/main/g8/.jvmopts, src/main/g8/build.sbt
+ Upgraded Twitter stacks: from 18.4.0 → 18.5.0
+ Fixed a ECR tagging issue
+ Added Scala 2.12.(5-6)’s performance tuning scalac option
+ Added JVM performance tuning properties `-XX:+UseG1GC -XX:+UseStringDeduplication` (https://dzone.com/articles/easy-change-to-reduce-memory-by-20)
=> Twitter 2018 May update

src/main/g8/build.sbt
Removed the settings of scoverage default on
=> Removed the scoverage default on

src/main/g8/build.sbt, src/main/g8/src/main/scala/$package__packaged$/Server.scala
+ added Splain compiler plugin
=> Splain compiler plugin

src/main/g8/src/main/scala/$package__packaged$/Server.scala, src/main/g8/src/test/resources/logback-test.xml
+ revised the order of Finatra Server filters to make trace id appear in logs
=> Log filter order fix

src/main/g8/default.properties
=> sbt upgrade

src/main/g8/src/test/resources/logback-test.xml
+ fixed a missing ‘$’ escape in the XML
=> logback-xml fix

src/main/g8/build.sbt
=> Dependency upgrades

src/main/g8/src/main/resources/logback.xml, src/main/g8/src/main/scala/$package__packaged$/Server.scala, src/main/g8/src/main/scala/$package__packaged$/controllers/MainController.scala, src/main/g8/src/main/scala/$package__packaged$/filters/ACLoggingFilter.scala, src/main/g8/src/main/scala/$package__packaged$/filters/CommonFilters.scala, src/main/g8/src/main/scala/$package__packaged$/models/http/GreetingsRequest.scala, src/main/g8/src/main/scala/$package__packaged$/services/SampleMessageService.scala, src/main/g8/src/test/scala/$package__packaged$/controllers/MainControllerFeatureTest.scala
+ fixed a case of double log entries
+ added Rerunnable’s raiseError use for example
+ health checking and version API no longer record access logs
=> logging-fix

src/main/g8/build.sbt, src/main/g8/mdoc-docs/how-tos/Env-Configs-Reading.md, src/main/g8/mdoc-docs/how-tos/PipeOperator.md, src/main/g8/src/main/scala/$package__packaged$/util/ConfigLib.scala
+ Upgraded Finatra-related lib
+ Added three more docs
=> april-2019-doc-dependent-lib-update

src/main/g8/build.sbt, src/main/g8/project/sbt-native-packager.sbt
* Fix OS updates (particularly in "multi-stage build mode)
* Remove `DOCKER_CONTENT_TRUST` as that is used by the `docker` CLI command, not inside a component
=> 2019/05 Updates from NetOPS

src/main/g8/project/plugins.sbt, src/main/g8/src/main/resources/log4j.properties, src/main/g8/src/test/resources/log4j-test.properties
Due to a logging issue (SLF4J bridge casting issue)
=> downgrade-microsites

src/main/g8/build.sbt, src/main/g8/project/plugins.sbt, src/main/g8/src/main/paradox/index.md
+ Added Paradox (static web site generator) support
=> May-29-update

src/main/g8/src/test/scala/$package__packaged$/StartupTest.scala
+ Change the location of the generated swagger.json (the location: under `target` directory)
=> swagger.json-location-change

src/main/g8/build.sbt, src/main/g8/default.properties, src/main/g8/project/plugins.sbt, src/main/g8/src/test/scala/$package__packaged$/problem/ProblemResponseSpec.scala
+ Upgraded Scala from 2.12.8 to 2.12.9
=> 2019-august-update-two

src/main/g8/project/plugins.sbt
+ removed coursier sbt plugin for sbt 1.3.0 upgrade
=> september-update-three-2019
